### ISSUE TITLE
Adding a version in another language uses the branch data source path

### ISSUE THREAD

**Issue by jsommr** [kamsar/BranchPresets#3]
When creating an item, BranchPresets correctly assigns the data source for the created version, but when creating a new version in another language, the data source points to the data source in the branch.

**Comment by Fillej** [comment]
I've got the same issue right now.

**Comment by kamsar** [comment]
The act of creating a new version doesn't cause a branch expansion to occur, so yes - Branch Presets won't be invoked when adding a language version to an existing item created from a branch preset.

There are three options:

1. (preferred) Set your branch layout on the _Shared Layout_ instead of the _Final Layout_. Shared layout is not language specific and will thus be expanded at branch time. It's possible to use final layout if the language layouts diverge thereafter.
2. Create language versions of the branch template and assign values there, instead of template standard values. This should cause expansion at branch time
3. Write an event handler that responds to `item:versionAdded` and expands the datasources then
